## Numpy
#### This is a library in python which is used to perform mathematical tasks
#### Also called Numerical-Python
#### Uses array for mathematical operations
#### Contiguos memory block that store Homogeneous Elements
#### Numpy is Much Faster Due to Vectorized operations and low-level C optimizations
#### Numpy Doesn't need loop to perform operations on each elements like lists, Supports Broadcast operations Directly
#### Numpy Uses less memory, especially for large datasets
#### Numpy offers a wide range of built in functions(eg: mean,std,dor,reshape)

In [41]:
import numpy as np

In [43]:
arr = np.arange(4) # Used to Generate an Array
print(a,type(a)) # Type is an Array

[0 1 2 3] <class 'numpy.ndarray'>


In [45]:
arr + 3 # Broadcasting Operation in Array, this can't be done using a List

array([3, 4, 5, 6])

In [47]:
arr.size # Tells number of elements

4

In [53]:
arr.shape # Tells Number of cols and rows

(4,)

In [57]:
arr[0] = 100
print(arr, type(arr))

[100   1   2   3] <class 'numpy.ndarray'>


In [69]:
arr1 = np.array([10,20,30])
arr2 = np.array([[10,20,30])
print(arr1.shape,arr2.shape)
print(arr1,arr2)

(3,) (2, 3)
[10 20 30] [[10 20 30]
 [40 50 60]]


In [75]:
arr3 = np.array([[10,20,30],
                [40,50,60]])
print(arr3.shape)
print(arr3)
print(arr3.reshape(3,2))

(2, 3)
[[10 20 30]
 [40 50 60]]
[[10 20]
 [30 40]
 [50 60]]


In [89]:
arr3 = np.array([
                [[50,60,70],
                [80,90,100],
                [110,120,130]]])
print(arr3.shape)
print(arr3)

(1, 3, 3)
[[[ 50  60  70]
  [ 80  90 100]
  [110 120 130]]]


In [95]:
arr4 = np.array([
                 [[10,20,30],
                  [40,50,60],
                 [1,2,3]],
                [[1,2,3],
                 [2,3,4],
                [4,5,6]]
])
arr4.shape

(2, 3, 3)

In [111]:
np.zeros((2,6)) # Creates array with elements only as zeroes

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [113]:
np.ones((2,6)) # Creates array with only ones as elements

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [121]:
arr5 = np.arange(10,dtype = 'float')
print(arr5)
arr5 = arr5.reshape(5,2)
print(arr5)

print(np.ones_like(arr5)) # Creates array similar to specifies arrays shape
print(np.zeros_like(arr5))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [127]:
arr6 = np.arange(1,10,2) # syntax: arange(start,end[excluded similar as before], step size)
print(arr6)

[1 3 5 7 9]
