## Numpy

In [171]:
pip install numpy

In [172]:
import numpy as np

In [173]:
# One-Dimensional Array
lst1 = [1,2,3,4,5]
arr1 = np.array(lst1)
print(type(arr1),arr1)
print(arr1.shape)

<class 'numpy.ndarray'> [1 2 3 4 5]
(5,)


In [174]:
# Multi-Dimensional Array
lst2 = [1,2,3,4,5]
lst3 = [4,5,6,7,8]
lst4 = [9,10,11,12,13]
arr2 = np.array([lst2,lst3,lst4])
print(arr2)
print(arr2.shape)
print(arr2.reshape(5,3))

[[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 9 10 11 12 13]]
(3, 5)
[[ 1  2  3]
 [ 4  5  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [175]:
# Indexing in Array
lst2 = [1,2,3,4,5]
lst3 = [4,5,6,7,8]
lst4 = [9,10,11,12,13]
arr2 = np.array([lst2,lst3,lst4])
# fetch[6,7]
#      [11,12]
print(arr2[1:,2:4])
# fetch [4,5]
      # [7,8]
print(arr2[:2,3:])
# fetch [2,3,4]
     #  [5,6,7]
     #  [10,11,12]
print(arr2[:,1:4])

[[ 6  7]
 [11 12]]
[[4 5]
 [7 8]]
[[ 2  3  4]
 [ 5  6  7]
 [10 11 12]]


## Inbuilt Functions of Numpy


In [177]:
# 1. arrange()
arr3 = np.arange(1,10,2)
print(arr3)

[1 3 5 7 9]


In [178]:
# 2. linspace()
arr4 = np.linspace(1,10,15)
print(arr4)

[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]


In [179]:
# 3. copy()
arr5 = np.copy(arr4)
print(arr5)

[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]


In [180]:
# 4. ones()
arr6 = np.ones(6)
print(arr6)

[1. 1. 1. 1. 1. 1.]


In [181]:
# 5. random.rand()
arr7 = np.random.rand(5,10)
print(arr7)

[[0.12863581 0.2416447  0.0719831  0.32319526 0.6399851  0.85228172
  0.76061182 0.74913856 0.87847749 0.1589556 ]
 [0.16201295 0.79173269 0.70344332 0.64048063 0.74055148 0.78170145
  0.04346276 0.02525656 0.17525048 0.51723169]
 [0.57908399 0.38247485 0.83155523 0.66045979 0.56980797 0.37482747
  0.70721704 0.57126507 0.62985987 0.67580746]
 [0.3059354  0.48964834 0.96149293 0.94783362 0.88287045 0.61284117
  0.23787533 0.76150656 0.8068563  0.58432029]
 [0.59881116 0.90421998 0.4089117  0.95595363 0.71449838 0.27434433
  0.90257499 0.94399481 0.60546221 0.17822852]]


In [182]:
# 6. random.randn()
arr8 = np.random.randn(3,3)
print(arr8)

[[-1.64727855 -0.83925901 -0.63666751]
 [-0.01417694 -2.41026551  0.7810195 ]
 [ 0.39913517  0.90003625 -0.46240496]]


In [183]:
# 7. random.randint()
arr9 = np.random.randint(3,50,7)
print(arr9)

[13 18 46 11 27 25 38]


In [184]:
# 8. random.random_sample()
arr10 = np.random.random_sample((2,5))
print(arr10)

[[0.85386188 0.40103834 0.00715643 0.88415403 0.45835438]
 [0.31122787 0.80555954 0.66834411 0.41066142 0.17835091]]
