In [1]:
import numpy as np
arr = np.array([[10,20,30],[40,50,60]])
print(arr)

[[10 20 30]
 [40 50 60]]


In [19]:
print(arr[0][1:])
print(arr[1][-2::-1])
print(arr[1][1:])

[20 30]
[50 40]
[50 60]


In [51]:
print(arr[0: ,0:2].flatten()) # arr[row: , cols:].flatten(): converts 2d array to 1d array

[10 20 40 50]


In [65]:
arr = np.array([[10,20,30],[40,50,60]])
# print(arr)
print(arr[(arr>25) & (arr<50)])

[30 40]


In [93]:
a = np.array([1,2,3])
b = np.array([5,6,7])
print(a+b)
print(b-a)
print(a*b)
print(a//b)
print(b%a)
print(b**a)
print(np.dot(a,b))

[ 6  8 10]
[4 4 4]
[ 5 12 21]
[0 0 0]
[0 0 1]
[  5  36 343]
38


In [89]:
# np.dot() function is used to find the Dot product
a = np.array([[1,2,3],[4,5,6]]) # 2d array dot product
b = np.array([4,5,6])
print(np.dot(a,b))

[32 77]


In [91]:
a = [[1,2],
    [3,4],
     [5,6] ]
b = [[1,2,3],
    [4,5,6]]
print(np.dot(a,b))

[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


In [99]:
data = np.array([[1,2],[3,4]])
print(np.sum(data))
print(np.mean(data))
print(np.min(data,axis=0)) # axis=0 works for column
print(np.max(data,axis=1)) # axos=1 works for rows

10
2.5
[1 2]
[2 4]


In [111]:
x = np.array([[1,2],
             [3,4]])
y = np.array([[5,6],[7,8]])
v = np.vstack((x,y))
h = np.hstack((x,y))
print(v)
print(h)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
