In [3]:
import numpy as np

In [5]:
# 1.Create a 1D NumPy array containing numbers from 1 to 5.\
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [7]:
arr.shape

(5,)

In [9]:
arr.dtype

dtype('int32')

In [11]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
arr = np.ones((2,2),dtype='int')
arr

array([[1, 1],
       [1, 1]])

In [17]:
arr = np.arange(10,51,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [25]:
arr = np.random.rand(5)
arr

array([0.56257854, 0.97094143, 0.2925461 , 0.91634373, 0.92510816])

In [27]:
arr = np.random.uniform(0,1,5)
arr

array([0.38466448, 0.75373994, 0.09236287, 0.24996655, 0.05497393])

In [31]:
arr = np.eye(4,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
arr[2,1]

80

In [37]:
arr[1,2] = 600

In [39]:
arr

array([[ 10,  20,  30],
       [ 40,  50, 600],
       [ 70,  80,  90]])

In [41]:
arr.reshape(1,9)

array([[ 10,  20,  30,  40,  50, 600,  70,  80,  90]])

In [43]:
arr = np.array_split(arr,3)
arr

[array([[10, 20, 30]]), array([[ 40,  50, 600]]), array([[70, 80, 90]])]

In [49]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr = np.array_split(arr,3)
arr

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [51]:
arr = np.array([[12, 43, 5],
                [7,  99, 21]])
np.max(arr)

99

In [53]:
np.min(arr)

5

In [55]:
np.argmax(arr)

4

In [57]:
np.argmin(arr)

2

In [59]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a*b

array([ 4, 10, 18])

In [61]:
# Matrix Mu;tiplication
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [63]:
a @ b

array([[19, 22],
       [43, 50]])

In [65]:
a = np.array([[1], [2], [3]])   # shape (3,1)
b = np.array([10, 20, 30])      # shape (3,)
a*b

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [67]:
arr = np.array([11, 22, 35, 40, 51, 60])
arr[arr%2==0]

array([22, 40, 60])

In [69]:
arr = np.array([10,20,30,40,50])
mean = np.mean(arr)
std = np.std(arr)
standarized = (arr-mean)/std
standarized

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [71]:
arr = np.array([1, 2, np.nan, 4])
np.isnan(arr)

array([False, False,  True, False])

In [77]:
np.isnan(arr).any()

True

In [79]:
np.isnan(arr).sum()

1

In [83]:
mean_val = np.nanmean(arr)
arr[np.isnan(arr)] = mean_val

In [85]:
arr

array([1.        , 2.        , 2.33333333, 4.        ])

In [89]:
arr[np.isnan(arr)] = mean_val


array([1.        , 2.        , 2.33333333, 4.        ])

In [99]:
arr = np.array([10, 26, 3, 50, 9])
arr = np.where(arr<25,99,arr)
arr

array([99, 26, 99, 50, 99])

In [111]:
arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
np.unique(arr,return_counts=True)

(array([1, 2, 3, 4]), array([1, 2, 3, 4], dtype=int64))

In [113]:
arr = np.array(np.random.randint(1,100,(5,5)))
arr

array([[34, 21, 59, 42, 84],
       [79, 33, 71, 44, 54],
       [32, 25, 69, 44, 84],
       [75, 60, 57, 60, 18],
       [36, 25,  1, 67, 48]])

In [115]:
arr = np.where(arr%2==0,0,arr)
arr

array([[ 0, 21, 59,  0,  0],
       [79, 33, 71,  0,  0],
       [ 0, 25, 69,  0,  0],
       [75,  0, 57,  0,  0],
       [ 0, 25,  1, 67,  0]])

In [117]:
arr = np.array(np.random.randint(1,101,(2,3,4)))
arr

array([[[ 17,  45,  55,  46],
        [ 33,  47,  54, 100],
        [ 22,  33,  81,  75]],

       [[ 65,  14,  83,  81],
        [ 75,  33,   8,  19],
        [ 50,  11,   6,  89]]])

In [121]:
arr = np.array([[12, 45, 78],
                [34, 11, 9],
                [90, 67, 5]])
arr = np.sort(arr,axis=1)
arr
arr = np.sort(arr,axis=0)
arr


array([[ 5, 11, 34],
       [ 9, 45, 78],
       [12, 67, 90]])

In [125]:
def label(x):
    return 'Even' if x % 2 == 0 else 'Odd'

arr = np.array([10, 15, 22, 33, 40])

v_label = np.vectorize(label)
v_label(arr)

array(['Even', 'Odd', 'Even', 'Odd', 'Even'], dtype='<U4')