In [3]:
# Q1: Create a 1D NumPy array of values from 0 to 9.
import numpy as np
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
arr = np.full((3,3),5)
print(arr)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [9]:
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
arr = np.arange(1,13)
np.reshape(arr,(3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
arr = np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [19]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])

[20 30 40]


In [21]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])
print(arr2d[1,1])

5


In [23]:
arr = np.array([10, 25, 30, 45, 60])
print(arr[arr>30])

[45 60]


In [25]:
arr = np.array([10, 25, 30, 45, 60])
print(arr[(arr>20) & (arr<50)])

[25 30 45]


In [27]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)

[5 7 9]


In [29]:
a = np.array([1, 2, 3])
a *= 3
print(a)


[3 6 9]


In [31]:
arr = np.array([10, 20, 30])
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.sum(arr))

30
10
20.0
60


In [47]:
arr = np.random.randint(0,9,size=(2,3))
print(arr)

[[1 9 9]
 [9 5 0]]


In [49]:
arr = np.arange(2,21,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


In [61]:
arr = np.reshape(np.arange(1,10),(3,3))
print(arr.flatten())

[1 2 3 4 5 6 7 8 9]


In [65]:
arr = np.array([15, 30, 45, 60, 75])
print(arr[(arr%3==0) & (arr%5==0)])

[15 30 45 60 75]


In [95]:
arr = np.random.randint(1,100,size=(4,4))
print(arr)
print()
print(arr[0],arr[:,-1])

[[15 56 66 71]
 [86 87 71  3]
 [84 88 26 94]
 [47 60 89 49]]

[15 56 66 71] [71  3 94 49]


In [109]:
arr = np.random.randint(50,100,10)
arr[arr>75] = -1
print(arr)

[-1 -1 -1 70 -1 -1 -1 -1 74 -1]


In [123]:
arr = np.array([[ 1,  2 , 3],
 [ 4 , 5,  6],
 [ 7 , 8 , 9]])
print(np.diag(arr))

[1 5 9]
